language: java
jdk:
  - openjdk17
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - bshevyrov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always